// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn3lxp7mPxTtxndRw08M1uHuaz2UxWOIs',
    appId: '1:608773292003:web:fcafd2bfd1095a1fb82ad6',
    messagingSenderId: '608773292003',
    projectId: 'smarteggtray',
    authDomain: 'smarteggtray.firebaseapp.com',
    databaseURL: 'https://smarteggtray-default-rtdb.firebaseio.com',
    storageBucket: 'smarteggtray.firebasestorage.app',
    measurementId: 'G-NF14FDGS29',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlMr3HuJoWgMhrvJsuSRBux_us5X4pXBc',
    appId: '1:608773292003:android:e44febff2767dca1b82ad6',
    messagingSenderId: '608773292003',
    projectId: 'smarteggtray',
    databaseURL: 'https://smarteggtray-default-rtdb.firebaseio.com',
    storageBucket: 'smarteggtray.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrm9YcOe1pB2By4nGJw1IHuD-NwtY9-_A',
    appId: '1:608773292003:ios:60c0c1bd14719b1cb82ad6',
    messagingSenderId: '608773292003',
    projectId: 'smarteggtray',
    databaseURL: 'https://smarteggtray-default-rtdb.firebaseio.com',
    storageBucket: 'smarteggtray.firebasestorage.app',
    iosBundleId: 'com.example.smarteggtray',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrm9YcOe1pB2By4nGJw1IHuD-NwtY9-_A',
    appId: '1:608773292003:ios:60c0c1bd14719b1cb82ad6',
    messagingSenderId: '608773292003',
    projectId: 'smarteggtray',
    databaseURL: 'https://smarteggtray-default-rtdb.firebaseio.com',
    storageBucket: 'smarteggtray.firebasestorage.app',
    iosBundleId: 'com.example.smarteggtray',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAn3lxp7mPxTtxndRw08M1uHuaz2UxWOIs',
    appId: '1:608773292003:web:dac145f0f8c3adbfb82ad6',
    messagingSenderId: '608773292003',
    projectId: 'smarteggtray',
    authDomain: 'smarteggtray.firebaseapp.com',
    databaseURL: 'https://smarteggtray-default-rtdb.firebaseio.com',
    storageBucket: 'smarteggtray.firebasestorage.app',
    measurementId: 'G-QT4R6ZN531',
  );
}
